### PR TITLE
#47 standardize citations

### LINKED ISSUE #47: Standardize citation style in function documentation
Some functions include references to journal publications or CIHI documents. This is currently inconsistently done across functions.

Having a reference section with consistent style will facilitate researchers in easily identifying the correct citations when using our package functions.

This issue is to:

- add a @references section to functions needed
- use consistent reference style. A concise style will be used for keeping documentation simple: [Author, Year]. (doi (whenever possible)/url)
- add this as a review item to  [Code Review Checklist](https://docs.google.com/document/d/16kiIgwWjXYhBM5AFToXD7X9OjqNYs0xQZh9VDfSwYQU/edit?usp=sharing).

### PR DESCRIPTION
**Pull request by gemini-wenb**
Closes #47 

This PR standardizes citation styles for `references` section in function documentation.

Notes:

Not all functions require a `references` section. To introduce some general structure to function documentation. The `references` section should typically be used when users are encouraged to include function-specific citations to their publications.
- Many functions contain links to extra resources in various sections (e.g. description, details). These resources are mostly links to data dictionary or CIHI documents. These resources may be regarded as general knowledge and specific citation may not be necessary (citing `Rgemini` would be sufficient). 
- Certain functions, especially derived scores, were developed based on journal publications which necessitate citations upon use. 
- For example, `frailty_score()` is developed based on a development paper, thereby, a citation is needed and it is included to the `references` section. Whereas, `icd_to_ccsr()` contains links to CIHI documentation of diagnosis definitions in function description, and these links don't need to be repeated in the `reference` section as they are not required citations.

Standard formatting style (aim to be simple):
- `Journal articles`: 1st_author_last_name initial, et al. Journal Abbrev, Year.  https://doi.org/xxxx (written out, no hyperlink, should use doi url instead of others like pubmed url).
- `Online doc`: [description] (hyperlink)

### CODE REVIEW

**Review by vaakesan-SMH — APPROVED** [review]
This looks good to me. Do we want to add our new citation/reference standards/requirements to `CONTRIBUTING.md`?

Also just confirming that we don't want to create hyperlinks to the DOI addresses in the roxygen?

**Comment by gemini-wenb** [comment]
> This looks good to me. Built the documentation and checked the rendered help pages. Do we want to add our new citation/reference standards/requirements to `CONTRIBUTING.md`?
> 
> Also just confirming that we don't want to create hyperlinks to the DOI addresses in the roxygen?:
> 
> image

Thanks for reviewing @vaakesan-SMH! Great idea to add the reference standard to the `CONTRIBUTING.md` - should we do this for this sprint or add this as a backlog issue? For not making DOI addresses into links, I tend to see the `References` section as the `References` list in journal publications, thus by not making DOI into links (which hides the actual DOI address) but showing them as they are makes the items similar to how actual citations would look like; this also distinguishes journal articles from online website resources - open to other ideas :)

**Comment by vaakesan-SMH** [comment]
Happy to leave the DOI addresses as-is. 

Lets update the `CONTRIBUTING.md` in this merge request.

**Comment by gemini-wenb** [comment]
> Happy to leave the DOI addresses as-is.
> 
> Lets update the `CONTRIBUTING.md` in this merge request.

Sounds good. Let me update that!

**Comment by vaakesan-SMH** [comment]
Looks good to me, thanks Bijun. Please go ahead and merge.

**Comment by gemini-wenb** [comment]
I've added a description of citation standard to `CONTRIBUTING`. I also added checking citation style to the `Code review checklist`. @vaakesan-SMH could you give it a quick check and if everything looks ok I'll merge the request. 
image

**Comment by vaakesan-SMH** [comment]
> I've added a description of citation standard to `CONTRIBUTING`. I also added checking citation style to the `Code review checklist`. @vaakesan-SMH could you give it a quick check and if everything looks ok I'll merge the request. image

looks great!

**Pull request merged**
